# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build & Static Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      # ===== STATIC ANALYSIS =====
      # SpotBugs
      - name: SpotBugs analysis
        run: mvn -Pspotbugs spotbugs:check

      # Checkstyle
      - name: Checkstyle analysis
        run: mvn checkstyle:check
        
      # ===== BUILD =====
      - name: Build with Maven
        run: mvn -B package

      # ===== TESTS =====
      - name: Run tests
        run: mvn test

      # ===== ARTIFACTS =====
      # - name: Upload JAR
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ocpp21-jar
      #     path: target/*.jar
